# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeNewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeNewsApp


  target 'ReactNativeNewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeNewsApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeNewsApp-tvOS

  target 'ReactNativeNewsApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
